# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, username, ... } : {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = { 
    device = "/dev/disk/by-uuid/ee4293e2-b7a8-4c89-af0f-a5cab5ee435d";
    fsType = "ext4";
  };

  fileSystems."/boot" = { 
    device = "/dev/disk/by-uuid/9189-D1E3";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # Extra drives

  # lsblk -f
  # NAME        FSTYPE FSVER LABEL      UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
  # sda                                                                                     
  # ├─sda1                                                                                  
  # ├─sda2      ntfs                    5C06844006841D60                                    
  # ├─sda3      vfat   FAT32            12B0-BF18                                           
  # └─sda4      ext4   1.0              e55fcd40-2a96-4ddd-80b4-a0f77e63bb55                
  # nvme0n1                                                                                 
  # └─nvme0n1p1 ntfs         New Volume FE7E8B9A7E8B4A7B                                    
  # nvme1n1                                                                                 
  # ├─nvme1n1p1 vfat   FAT32            9189-D1E3                             961.1M     6% /boot
  # └─nvme1n1p2 ext4   1.0              ee4293e2-b7a8-4c89-af0f-a5cab5ee435d  804.9G     7% /nix/store

  fileSystems."/home/${username}/driveBig" = { 
    device = "/dev/disk/by-uuid/FE7E8B9A7E8B4A7B";
    fsType = "ntfs-3g";
    options = [ 
      "rw" 
      "uid=1000"  # Your user ID (usually 1000 for first user)
      "gid=100"   # users group
      "dmask=0022" 
      "fmask=0022"
      "big_writes"
      "windows_names"
    ];
  };

  fileSystems."/home/${username}/driveArch" = { 
    device = "/dev/disk/by-uuid/e55fcd40-2a96-4ddd-80b4-a0f77e63bb55";
    fsType = "ext4"; # Change to your filesystem type
    options = [ "nofail" "x-systemd.device-timeout=1" ]; # To no throw a tantrum and to not wait 1.5min before throwing it
  };

  # mount -o gid=users,fmask=113,dmask=002 /dev/sdb1 ~/driveUSB for usb drives

  swapDevices = [{
    device = "/swapfile";
    size = 32 * 1024; # 32GB
  }];

  # sudo filefrag -v /swapfile | head                    use this to find offset                          
  #   Filesystem type is: ef53
  #   File size of /var/lib/swapfile is 68719476736 (16777216 blocks of 4096 bytes)
  #   ext:     logical_offset:        physical_offset: length:   expected: flags:
  #     0:        0..    2047:  576098304.. 576100351:   2048:            
  #                             --------- this is the one!
  #     1:     2048..    4095:   74756096..  74758143:   2048:  576100352:
  #     2:     4096..    6143:   71784448..  71786495:   2048:   74758144:
  #     3:     6144..   12287:   71788544..  71794687:   6144:   71786496:
  #     4:    12288..   71679:  100237312.. 100296703:  59392:   71794688:
  #     5:    71680..  434175:  100300800.. 100663295: 362496:  100296704:
  #     6:   434176..  466943:  100204544.. 100237311:  32768:  100663296:
  boot.kernelParams = [ "mem_sleep_default=deep" "resume_offset=91133952" ];

  # use lsblk -f to get uuid of root
  boot.resumeDevice = "/dev/disk/by-uuid/ee4293e2-b7a8-4c89-af0f-a5cab5ee435d";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}