# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/86fd6f62-06f5-4b2c-ac58-ae62eab33f0a";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/50B1-DC78";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };


  fileSystems."/home/adam/driveBig" = { 
    device = "/dev/disk/by-uuid/4d36aeec-04e7-47f8-b05f-9d76e9c0b8a4";
    fsType = "ext4"; # Change to your filesystem type
    options = [ "nofail" "x-systemd.device-timeout=1" ]; # To no throw a tantrum and to not wait 1.5min before throwing it
  };

  swapDevices = [{
    device = "/swapfile";
    size = 16 * 1024; # 16GB
  }];

  boot.kernelParams = [ "resume_offset=921600" ];

  boot.resumeDevice = "/dev/disk/by-uuid/86fd6f62-06f5-4b2c-ac58-ae62eab33f0a";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
